// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrdvFP67lBmXt2TMY3w2KzX5fHVKgrd7g',
    appId: '1:21720213710:web:83650b75c16e058aae089f',
    messagingSenderId: '21720213710',
    projectId: 'metropol-8aa1b',
    authDomain: 'metropol-8aa1b.firebaseapp.com',
    storageBucket: 'metropol-8aa1b.firebasestorage.app',
    measurementId: 'G-71MLCVTD0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRDj06dGNrHUb-nuCUOmKaHXUNjXEUzQU',
    appId: '1:21720213710:android:dc693c59c09d9733ae089f',
    messagingSenderId: '21720213710',
    projectId: 'metropol-8aa1b',
    storageBucket: 'metropol-8aa1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQobMShb790jSSZw81boyRMFYBfTsZyLk',
    appId: '1:21720213710:ios:b0f37a24dd9e729bae089f',
    messagingSenderId: '21720213710',
    projectId: 'metropol-8aa1b',
    storageBucket: 'metropol-8aa1b.firebasestorage.app',
    iosBundleId: 'com.metropol.metropolMawandaPeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQobMShb790jSSZw81boyRMFYBfTsZyLk',
    appId: '1:21720213710:ios:b0f37a24dd9e729bae089f',
    messagingSenderId: '21720213710',
    projectId: 'metropol-8aa1b',
    storageBucket: 'metropol-8aa1b.firebasestorage.app',
    iosBundleId: 'com.metropol.metropolMawandaPeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrdvFP67lBmXt2TMY3w2KzX5fHVKgrd7g',
    appId: '1:21720213710:web:797054353b44b2eeae089f',
    messagingSenderId: '21720213710',
    projectId: 'metropol-8aa1b',
    authDomain: 'metropol-8aa1b.firebaseapp.com',
    storageBucket: 'metropol-8aa1b.firebasestorage.app',
    measurementId: 'G-0C2K3VGVF7',
  );
}
